services:
  flask_app:
    build: .
    ports:
      - "${FLASK_APP_PORT}:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@flask_db/${MYSQL_DATABASE}
    depends_on:
      flask_db:
        condition: service_healthy
    volumes:
      - .:/app

  flask_db:
    image: mariadb:10.11
    restart: always
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dados:/csv_data
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./load_data.sh:/docker-entrypoint-initdb.d/2-load_data.sh

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 120s

volumes: 
  db_data:
